/**
 * Type definitions for AI service
 */

/**
 * AI provider types
 */
export type AIProvider = 'openai' | 'gemini';

/**
 * Configuration for AI service
 */
export interface AIServiceConfig {
  provider: AIProvider;
  apiKey: string;
  model?: string;
  maxRetries?: number;
  timeout?: number;
}

/**
 * Request for AI content generation
 */
export interface GenerationRequest {
  prompt: string;
  context: string;
  wordCount?: number;
  questionCount?: number;
}

/**
 * Response from AI content generation
 */
export interface GenerationResponse {
  answers: Answer[];
  totalWords: number;
  provider: AIProvider;
  model: string;
}

/**
 * Individual answer generated by AI
 */
export interface Answer {
  questionNumber: number;
  content: string;
  wordCount: number;
}

/**
 * Parsed prompt information
 */
export interface ParsedPrompt {
  originalPrompt: string;
  wordCount?: number;
  questionCount?: number;
  questions: string[];
}

/**
 * Custom error class for AI generation failures
 */
export class AIGenerationError extends Error {
  constructor(
    message: string,
    public retryable: boolean,
    public code: AIGenerationErrorCode,
    public provider?: AIProvider,
    public originalError?: Error
  ) {
    super(message);
    this.name = 'AIGenerationError';
    Object.setPrototypeOf(this, AIGenerationError.prototype);
  }
}

/**
 * Error codes for AI generation
 */
export enum AIGenerationErrorCode {
  INVALID_API_KEY = 'INVALID_API_KEY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  CONTENT_FILTER = 'CONTENT_FILTER',
  INSUFFICIENT_QUOTA = 'INSUFFICIENT_QUOTA',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  PARSING_ERROR = 'PARSING_ERROR',
}

/**
 * Retry configuration
 */
export interface RetryConfig {
  maxRetries: number;
  initialDelay: number;
  maxDelay: number;
  backoffMultiplier: number;
}
